// Module included in the following assemblies:
//
// * service_mesh/service_mesh_install/installing-ossm.adoc

[id="ossm-control-plane-deploy_{context}"]

= Deploying the control plane

With the introduction of {product-title} 4.1, the network capabilities of the host are now based on nftables rather than iptables. This change impacts the initialization of the {ProductName} application components. {ProductShortName} needs to know what host operating system OpenShift is running on to correctly initialize {ProductShortName} networking components.

[NOTE]
====
You do not need to follow this procedure if you are using {product-title} 4.1.
====

If the OpenShift installation is deployed on a Red Hat Enterprise Linux (RHEL) 7 host, then the custom resource must explicitly request the RHEL 7 `proxy-init` container image by including the following:

.Enabling the proxy-init container for RHEL 7 hosts

[subs=+macros]
----
  apiVersion: maistra.io/v1
   kind: ServiceMeshControlPlane
   spec:
     istio:
       global:
        pass:quotes[*proxy_init:*]
          pass:quotes[*image: proxy-init*]
----

Use the custom resource definition file you created to deploy the {ProductShortName} control plane.


.Procedure

. Create a custom resource definition file named `istio-installation.yaml`.

. Run this command to deploy the control plane:
+
----
$ oc create -n istio-system -f istio-installation.yaml
----

. Run this command to watch the progress of the pods during the installation process:
+
----
$ oc get pods -n istio-system -w
----

= Deploying the control plane using OperatorHub

.Prerequisites

* An account with maistra-admin access (needs to be confirmed).

* The {ProductName} Operator must be installed.

.Procedure

* Create a new project in the OpenShift Container Platform web console for this procedure. This example uses a project called istio-system.

* Navigate to the Catalogs → Installed Operators page.

* On the Installed Operators page, click Copied, and then click the {ProductName} Operator to view more details and available actions:
 * As shown under Provided APIs, this Operator makes available two resource types: one for a {ProductName} ControlPlane and the other one for a ServiceMeshMemberRoll.

* Create a new {ProducName} control plane:
 
 * In the "Istio Service Mesh Control Plane" box click "Create New"
 
 * The next screen allows you to make any modifications to the minimal starting template of an ServiceMeshControlPlane object, such as the size of the cluster. Click Create to finalize. This triggers the Operator to start up the Pods, Services, and other components of the new {ProductName} control plane.

* Click "Istio Service Mesh Control Plane" tab, then click on the name of the control plane that was just created

* Click the Resources tab to see {ProductName} control plane resources created and configured automatically by the Operator.

